name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: linaalami
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: linaalami/lina:latest

      - name: Run container and test
        run: |
          docker run -d -p 8080:80 --name test-lina linaalami/lina:latest
          sleep 10
          curl -f http://localhost:8080 || exit 1
          docker stop test-lina
          docker rm test-lina
